---
-
 name: Trabalhando com tags
 hosts: web
 remote_user: ansible
 become: yes

 tasks:
   - name: instala httpd e memcached ou configura
     yum: name={{ item }} state=installed
     with_items:
       - httpd
       - memcached

     tags:
       - packages
       - template: src=templates/src.j2 dest=/etc/foo.conf

     tags:
       - configuration
